### ISSUE TITLE
Cannot Access RazeMath

### ISSUE THREAD

**Issue by Evan-McCall** [rkhettry/llm-math-public#16]
This morning when I tried to access RazeMath, both via the testing URL and the normal razemath.streamlit.app URL, I received the following message which prevented me from using the app:

![Screenshot 2024-11-30 at 10 29 06 AM](https://github.com/user-attachments/assets/75627007-5547-411e-9ec4-f912e8e9cfa3)

**Comment by rkhettry** [comment]
Seems like there was a python requirement conflict. It is now resolved
