### ISSUE TITLE
New Problem Summary Description

### ISSUE THREAD

**Issue by Evan-McCall** [rkhettry/llm-math-public#23]
Here is the new problem summary description that hopefully prevents the glazing that it was doing before:

prompt = f"""
The student has completed solving the following problem:

Problem: {solution.original_problem}

Here is their performance on each step:
{steps_info}

Provide a summary that:
Starts with a brief pleasantry. (e.g. “Great job!”)
States the specific concepts, formulas, or topics that the student correctly used in their solution.
Points out the specific step(s) that the student made a mistake on, and what the mistake was.
Gives the student specific topics to study further based on the mistakes made in the previous problem.
Ends with another brief pleasantry that motivates the student to keep studying and learning about the areas they need to improve on.

Make sure the problem summary:
-Gives the student relevant recommendations about what to study next based on their mistakes in the previous problem, with the objective that these topics will help them score better on their exams.
-Is written concisely. It should follow the given structure while also not being too verbose.
-Is written in a gentle and patient tone. Be empathetic, but don’t be overly pleasant or motivational. Simple pleasantries at the start and end are enough.
-Does not reveal any additional answers or solutions.
-Recommends that the student keep studying the same topic or similar if they made no mistakes.
"""

**Comment by svante92** [comment]
Replaced old prompt with this one.
